### ISSUE TITLE
Provide feedback to stdout when profile is pushed

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#109]
**Is your feature request related to a problem? Please describe.**
When the "-p" option is used to push a profile, there is no output to the screen indicating that the push was successful unless you run with "-v".  

**Describe the solution you'd like**
Add a message stating that the profile was pushed to <URL> succesfully.

**Comment by rsdunlapiv** [comment]
Not needed for v0.1.1 - just getting this down now.

**Comment by ryanlong1004** [comment]
![image](https://user-images.githubusercontent.com/69773028/142708068-60546712-393e-4701-885b-3969e947f97c.png)
