### ISSUE TITLE
Web files not copied into output when profiler is run outside of the root installation directory

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#168]
**Describe the bug**
Running the profiler outside of the root installation directory causes the ./web/app/build files not to be copied into the output.  This is due to use of a file path relative to the esmf-profiler root.

**To Reproduce**
Run the profiler outside the esmf-profiler root.  You see:
```
2022-01-07 17:38:24,619 : INFO : esmf_profiler.main : Trace processing time: 0.1s
Traceback (most recent call last):
  File "/glade/scratch/dunlap/esmf-profiler/venv/bin/esmf-profiler", line 33, in <module>
    sys.exit(load_entry_point('esmf-profiler', 'console_scripts', 'esmf-profiler')())
  File "/glade/scratch/dunlap/esmf-profiler/src/esmf_profiler/main.py", line 306, in main
    copy_gui_template(output_path)
  File "/glade/scratch/dunlap/esmf-profiler/src/esmf_profiler/main.py", line 177, in copy_gui_template
    raise FileNotFoundError()
FileNotFoundError
```

**Expected behavior**
Since esmf-profiler is in the path, you should be able to run it from any directory and it should know where to find the web app files.

One option might be to use the `package_data` option under `setup.py` to install the web files.

**Comment by rsdunlapiv** [comment]
Testing the development branch after PR #169, I find that the absolute path is applied to both the source and the destination when copying the web files.  This means that no matter which directly I run the profiler in, the output appears under esmf-profiler/src/esmf-profiler.  E.g.:

```
(venv) dunlap@cheyenne5:/glade/scratch/dunlap> esmf-profiler -t ./esmf-profiler/tests/fixtures/test-traces/atm-ocn-concurrent/ -o ./floss -n me -v
```
Here I would expect the ./floss directory to be under /glade/scratch/dunlap

However, the files are copied here:

```
Copied file /glade/scratch/dunlap/esmf-profiler/web/app/build/static/js/runtime-main.e545169b.js.map to /glade/scratch/dunlap/esmf-profiler/src/esmf_profiler/./floss/static/js
```

The path to the destination should remain *relative* to where the user runs the esmf-profiler.

**Comment by ryanlong1004** [comment]
Fixed in updated branch.  

See image below to verify.

![image](https://user-images.githubusercontent.com/69773028/148868255-7b95e46d-759e-4477-95fb-01797e630178.png)
