### ISSUE TITLE
gcc requirement is 9.0.0, should be >9

### ISSUE THREAD

**Issue by ryanlong1004** [esmf-org/esmf-profiler#32]
@rsdunlapiv 

I think the code is looking for an exact match for gnu 9.0.0, but anything above 9 is fine.

https://github.com/esmf-org/esmf-profiler/blob/development/install_dependencies.sh

**Comment by rsdunlapiv** [comment]
@ryanlong1004 this is using the "sort" command, so it is looking for >9

**Comment by rsdunlapiv** [comment]
dumpversion might be easier to parse:

```
rocky@rocky-Latitude-E5570:~/esmfdev/esmf-profiler.ryan$ gcc -dumpversion
10
rocky@rocky-Latitude-E5570:~/esmfdev/esmf-profiler.ryan$ gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

What is the issue you are trying to resolve?  Do you have a case where there is a valid version of gcc and it is failing to capture it?

**Comment by rsdunlapiv** [comment]
Okay, I understand.  Definitely looks like something that needs to be debugged.
