### ISSUE TITLE
Add build argument to Dockerfile to select branch of esmf-profiler to clone

### ISSUE THREAD

**Issue by ryanlong1004** [esmf-org/esmf-profiler#36]
In the Dockerfile, change the ```git clone``` command to clone from master after initial release.

**Comment by rsdunlapiv** [comment]
Updated this issue.  Add an build argument to the Dockerfile so the user can configure which branch of esmf-profiler to check out.  Right now it uses main.  That should remain the default if the build argument is not provided.

**Comment by rsdunlapiv** [comment]
When this issue is completed, we need to update the [test procedure](https://github.com/esmf-org/esmf-profiler/wiki/Testing-Procedures) to use the build argument to point to the "development" branch when testing the Dockerfile.

**Comment by rsdunlapiv** [comment]
@ryanlong1004 can this be closed?
