### ISSUE TITLE
Do we need the bt2 Python Library?

### ISSUE THREAD

**Issue by rlongio** [esmf-org/esmf-profiler#4]
Do we need to use the bt2 python module?  If all the data you need is spit out the same as just using babeltrace2, I think we could abstract out the python module and just call babeltrace2 from python and collect the results in memory / tmp space etc.  

But maybe it's offering something I don't understand.

**Comment by rsdunlapiv** [comment]
Two things come to mind that we'd need to look into:
- Performance - some traces contain a lot of events, so we'd need to understand whether running bt2 separately to generate the event stream and passing it into Python has performance implications.  
- Parsing the events themselves - the Python API provides specific data structures for events that allows you to access the individual fields in the event.  How would this be handled if we do not use the python bt2 API?

**Comment by rsdunlapiv** [comment]
We decided to avoid text-based processing for performance considerations, especially for large traces.
