### ISSUE TITLE
Install version reported from pip should match tag

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#54]
**Describe the bug**

Installing version 0.1 of the esmf-profiler shows this:
```
Installing collected packages: profiler
  Attempting uninstall: profiler
    Found existing installation: profiler 0.0.1
    Uninstalling profiler-0.0.1:
      Successfully uninstalled profiler-0.0.1
  Running setup.py develop for profiler
Successfully installed profiler
```

**To Reproduce**
Run the installation script.

**Expected behavior**

(1) the name of the package should be "esmf-profiler" (not "profiler")
(2) the version reported should match the repo tag (0.1 instead of 0.0.1) and should always stay synced

**Comment by ryanlong1004** [comment]
Added **tag.sh** into development branch.

The script takes the version from setup.py and creates a tag and commits it to git.
