### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#55]
**Describe the bug**

The docker build command fails:

```
Step 7/12 : RUN git clone -b https://github.com/esmf-org/esmf-profiler.git
 ---> Running in ec127b66bf8d
fatal: You must specify a repository to clone.

usage: git clone [<options>] [--] <repo> [<dir>]
```

**To Reproduce**
Run the docker build from the quick start: 
```
docker build -t esmf-profiler-image .
```

**Expected behavior**
The docker build should succeed.

It appears that the issue is the "-b" argument to `git clone` is expecting a branch name, but none is provided.  From the Dockerfile:
``` 
RUN git clone -b https://github.com/esmf-org/esmf-profiler.git
```

This should either clone the default branch, or be hard-coded to main branch, or potentially be a build argument to docker.  (To allow the user to select which branch to build from.)

**Comment by ryanlong1004** [comment]
@rsdunlapiv this has been resolved.

There is now the issue of having a specific version installed in the container.

I've tried this with the [deadsnakes repo with no success.](https://stackoverflow.com/questions/66597894/why-cannot-add-ppa-deadsnakes).  

The other option is to include the source for the version of python alongside the other dependencies and build/install it to the image same as BT2.

This is also going to mean changing the ```install.sh``` to install a virtual environment using the version of Python we built (we'll have to specify vs. the now default).
