### ISSUE TITLE
Fails to view static site locally

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#58]
**Describe the bug**

After generating a profile, I try to view the static site locally by navigating to the index.html file on my local file system and opening it directly in Chrome.

I see the following error in the Chrome console:
```
Report.jsx:22 Fetch API cannot load file:///home/rocky/esmfdev/esmf-profiler.v1/tests/fixtures/test-traces/output/data/load_balance.json. URL scheme "file" is not supported.
l @ Report.jsx:22
Report.jsx:39 Fetch API cannot load file:///home/rocky/esmfdev/esmf-profiler.v1/tests/fixtures/test-traces/output/site.json. URL scheme "file" is not supported.
(anonymous) @ Report.jsx:39
```

**To Reproduce**
Generate a profile and try to open the static site from the local file system from Chrome.

**Expected behavior**
The static site should be viewable locally.  Not all users will want to push to GitHub.io or a web server.

This issue seems to discuss the problem and offers a solution, albeit one that looks complex:
https://stackoverflow.com/questions/49971575/chrome-fetch-api-cannot-load-file-how-to-workaround

**Comment by rsdunlapiv** [comment]
In a related issue, the fetch() for the site.json is trying to fetch:
`output/site.json`

but instead should be:
`output/data/site.json`

**Comment by ryanlong1004** [comment]
@rsdunlapiv This is a browser issue from your link and the other articles I've read.  

Options
1.  Run ```chrome --allow-file-access-from-files``` when viewing the reports locally. 
2.  Include a small python local server; the user would enter a command that would spin up the server locally and launch the site (https://docs.python.org/3.6/library/http.server.html#http.server.SimpleHTTPRequestHandler)
3. Push ```data``` to a public repo and access them that way

We verified this worked at some point.  I changed, then removed the Router thinking that was the issue, but it wasn't.

Not closing yet.

**Comment by rsdunlapiv** [comment]
What are the options if we do not use fetch()?

**Comment by ryanlong1004** [comment]
This worked when we built the report including the files:
![image](https://user-images.githubusercontent.com/69773028/140201139-cf8e633d-7708-4645-bf86-9f350a4d3e4a.png)

**Comment by rsdunlapiv** [comment]
But doesn't that mean that we would need the data/*.json files when the static site is built?  Or does that dynamically bring in the .json files even after the site has been built?

**Comment by ryanlong1004** [comment]
The would be built in to the report, otherwise would be a CORS violation.

**Comment by ryanlong1004** [comment]
@rsdunlapiv python comes with a built in simple http server that requires no installation.  You can test it out by running it in the ```htmlcov``` directory after running pytest.

```bash
python -m http.server --directory htmlcov
```
