### ISSUE TITLE
install_dependencies.sh fails on Hera

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#94]
**Describe the bug**
install_dependencies.sh fails on NOAA/Hera.

```
Making install in py-common
make[2]: Entering directory `/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/dependencies/babeltrace2-2.0.4/src/py-common'
  CC       py-common.lo
In file included from py-common.c:31:
/apps/oneapi/intelpython/python3.7/include/python3.7m/Python.h:160:5: error: "_MSC_VER" is not defined, evaluates to 0 [-Werror=undef]
  160 | #if _MSC_VER
      |     ^~~~~~~~
/apps/oneapi/intelpython/python3.7/include/python3.7m/Python.h:162:7: error: "__clang__" is not defined, evaluates to 0 [-Werror=undef]
  162 | #elif __clang__ || __GNUC__
      |       ^~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [py-common.lo] Error 1
make[2]: Leaving directory `/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/dependencies/babeltrace2-2.0.4/src/py-common'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler/dependencies/babeltrace2-2.0.4/src'
make: *** [install-recursive] Error 1
Removing install directories
SUCCESS
```

Modules I have loaded:

```
[Rocky.Dunlap@hfe05 dependencies]$ module list

Currently Loaded Modules:
  1) gnu/9.2.0   2) intelpython/2021.3.0
```

SUCCESS is also reported at the bottom, although the script failed.

**To Reproduce**
Log in to Hera and run the ./install_dependencies.sh script.

**Expected behavior**
install_dependencies.sh should complete succesfully

**Comment by rsdunlapiv** [comment]
Adding `--disable-Werror` to the BT2 configure line gets passed the error:
./configure --prefix=$PWD/../INSTALL/$BT2 --enable-static --enable-python-bindings --enable-python-plugins --disable-man-pages --disable-debug-info --disable-Werror
But it fails later with an internal compiler error.

**Comment by rsdunlapiv** [comment]
When I unload the intelpython module, the install_dependencies.sh is successful, even without the extra `--disable-Werror` argument to BT2 config.

@ryanlong1004 for this release I recommend we state in the release notes that intelpython is not supported.  It might be that babeltrace2 python bindings cannot be built against intelpython.  This will require some further investigation.

**Comment by ryanlong1004** [comment]
@rsdunlapiv this installed the other day clean and I just tested it again on Hera.

The only module load was gnu/9.2.0.  The default loaded python works fine.

I'll add the _intelpython_ not supported to the release notes.

**Comment by ryanlong1004** [comment]
Created ticket.

https://github.com/esmf-org/esmf-profiler/issues/97
