### ISSUE TITLE
Package name should be 'esmf-profiler' not 'profiler'

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#95]
The package name installed by pip is 'profiler'

```
[venv] [Rocky.Dunlap@hfe05 esmf-profiler]$ pip install -e .
Obtaining file:///scratch2/NCEPDEV/stmp1/Rocky.Dunlap/esmf-profiler
Installing collected packages: profiler
  Running setup.py develop for profiler
Successfully installed profiler
```

The name should be 'esmf-profiler' to prevent confusion with other profiling applications.

**Comment by ryanlong1004** [comment]
@rsdunlapiv this was a design decision so that the application itself would be branded but the package itself would not be.

I'll revert and commit now.

**Comment by ryanlong1004** [comment]
Updated.

https://github.com/esmf-org/esmf-profiler/commit/d6c61e017c5c1960d9ef506bcc021c643915186f

**Comment by rsdunlapiv** [comment]
Thanks @ryanlong1004.  It looks like the CI/pytest need to be updated with the name change.
