### ISSUE TITLE
Update quick start guide with new section 'Generating and Viewing Profiles'

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/esmf-profiler#99]
The quick start guide covers installation, but does not have a section on actually generating a profile from a trace.  Add a section that covers the basic cases:

1.  Generate a profile and view locally
2.  Generate a profile and push it to GitHub.io for sharing

In the case of 1, we need to be clear that the user will need to be able to bind to port 8000, so this option is only supported on local machines like laptops and desktops.  Most HPC options will not support this option and must use the push option.

**Comment by rsdunlapiv** [comment]
The doc should also specify whether the browser is expected to open automatically or if the user should manually navigate to localhost:8000.

**Comment by ryanlong1004** [comment]
https://github.com/esmf-org/esmf-profiler/commit/2ca7a15241e5e59ef5f40719291ecbf28393ef01
